name: Deploy to Server

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: self-hosted
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Build and Restart Docker Containers
        run: |
          docker-compose up -d --build
